### ISSUE TITLE
Class changes during development require me to shut down and restart the server to accept the changes

### ISSUE THREAD

**Issue by binotby** [creativetimofficial/material-tailwind-dashboard-react#25]
Class changes during development require me to shut down and restart the server to accept the changes, otherwise the class I'm using is unreadable, it's like I'm running production when I'm running development.

Does anyone have a solution for this problem?

**Comment by binotby** [comment]
For example i am using ml-40 and i change to ml-20 to see the change i have to shut down and run the server `yarn start` again

**Comment by binotby** [comment]
@sajadevo @einazare if you have a little time please help me :)

**Comment by sajadevo** [comment]
@binotby could you please check the latest version it should be fixed.
